services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CONTEXT_PATH=${NEXT_PUBLIC_CONTEXT_PATH}
      - NEXT_PUBLIC_JWT_SECRET=${NEXT_PUBLIC_JWT_SECRET}
    restart: unless-stopped
    networks:
      - bus-network

networks:
  bus-network:
    external: true