services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_CONTEXT_PATH=${NEXT_PUBLIC_CONTEXT_PATH}
      - NEXT_PUBLIC_JWT_SECRET=${NEXT_PUBLIC_JWT_SECRET}
    restart: unless-stopped
    networks:
      - bus-network

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - "${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro"
  #   depends_on:
  #     - frontend
  #   restart: unless-stopped
  #   networks:
  #     - bus-network

networks:
  bus-network:
    external: true